@echo off
echo Launching Android Emulator (Pixel_6a)...
flutter emulators --launch Pixel_6a
echo Waiting for emulator to start...
timeout /t 10
echo Running Flutter App...
flutter run -d emulator-5554
