services:
  - type: web
    name: leox-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: studio-7488920972-4ef9c
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@studio-7488920972-4ef9c.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        value: |-
          -----BEGIN PRIVATE KEY-----
          MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCkVZMT5g4ELYGb
          okvhSvkmNz0jx47tD1Do4jfk9ey9xpEZyMX/gRw4YBWY2uhus1KHto6P4PwRp0/I
          wOyNSaKEzHRoDL1tzD13mk/IymBwGUgpY2CVTCXH99sZXGrKEDv0DKH95kpRM8ay
          TR3agBiZmGOA0AdF7cjVtonea5PVxJTh5U/ocpEAMSpwV+LvBFInacmpGNRStvkV
          hSCtqTQHYUdYwBKXRir6uPF+HKRz64WmOkQAodsAj/dsLqJKZeAIc8ropaUVwUKR
          pFw9vwPj27nWsiEu+1sDyD1q6gKFSmiRcQgE2+P5zW00W2ks6FaaD09VqCbsMXvz
          5dy2fKsFAgMBAAECggEABis7ibAwT4Irzt1WpDRDH7xMHGyQgMql5WV0kVuVUaxu
          Dv3lR4mftxK4TNQkNzTzwKoe4Od3tEFHx/KiDqMN1EFej0yxzGOHMoGwRAqAze8i
          W9diAp4TVFXeu4LSHsK26sWR9oIva6vvZgsUt0/pXH6xdt5C9PePpfd5ER3ltKJh
          7nUBLenjXd9dCO/rp54ACnVbZ/W9oSWKcK4X9btIqN4jpOoxL6yXa07n6W+WhUW/
          zFZnHF5q02Z+nwK/h7870zbjSlG92TOykETeURDhIQ5YwdCUZEI6VH4Zh+x+9Y8e
          Uag6ZgEqGrm6SMIefY895wQiFFTeFH7DL60YauTLQwKBgQDYdslr6P70bF+MIyYp
          1puVo1GJqV8hckUZq53REzUja2naaDQ61s88lAfN6Hb+8OSJUOhl8jU9/Auq+QC7
          sHJgWaCzheyx+YbTlQLv7SMuEVk2Eho41WvdCACHN8w/JX3hIIYqc+WqAcXj0TLp
          MXGJ6qUxXrQWz66BzaWDjG321wKBgQDCWVs6+0PR4UiMh0Niz1yUcM12t8EGiKMH
          9LsSXbXOYL5miNFGDMMgbcTM50NiuJs+XcwE/2/e9RU26Mu3wijSK+6hrKtweKli
          PkN3mDt1DhpWYcFabnsoKi4RUTz+JNeN99Lf1NGEbw34TBohopd6S+WN+CxDcY+M
          ng/quacdgwKBgQC7cqIaADpID1DuWcHCmUVB35vMSg9HN1z/Tc3sL2Xkti+EIpiY
          G0x6ePYJKTVir9g30Qhuv7+7XXf9JoOsBLAHH5Y538+IjzxiHLfebMv6KKvIVwS+
          EpLFZRiP/5GvXRgUy8VjHdnTzpU/IvmjVl2rwLYseoYY+t9zKFIcCI9xIQKBgQCw
          WHgpWpi9NheoO4vveoxcvMYSNMXW8eBMdcnQ7mrrKmlZjEensijTogZyjl1clHl4
          648V8dlGi0eGnVFMGccEfYx38r9UvIeldy2stNsuaW+IdgcF0T26whsu53HagP99
          +CLFqsu5yTL528PSRUABXiCa41b2k3JXe4yhxXdXlQKBgChHKzG3o6bJKgs80eUO
          Y9URVc5LZZNdR6n4E/OfEL4GrtQj1Zm/wBhUMQxPYgtDwsQ69+Q54dJcEMsZcxkq
          8Qsiq+tqal++JBaFDIQYiLnXWf/stKiY4tmHFv/advqBRciMISWeN8s4wPXMXhib
          JvucNXStNA/pqE9Z1nFdY5xT
          -----END PRIVATE KEY-----
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TEtiqwUIhnWfVg
      - key: RAZORPAY_KEY_SECRET
        value: 96u9x1V0WVZGJQcyx3pdn0Kt
      - key: OPENAI_API_KEY
        value: your-openai-api-key-here
      - key: OPENAI_MODEL
        value: gpt-4-turbo