platform :ios, '11.0'

# CocoaPods helpers.
flutter_ios_podfile_setup = File.join(File.dirname(File.expand_path(__FILE__)), 'Flutter', 'podhelper.rb')
require flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # Strip unsupported -G compiler/linker flag from target configurations
      ['OTHER_CFLAGS', 'OTHER_LDFLAGS', 'OTHER_SWIFT_FLAGS', 'GCC_PREPROCESSOR_DEFINITIONS'].each do |key|
        val = config.build_settings[key]
        next if val.nil?
        if val.is_a?(Array)
          val.delete('-G')
        elsif val.is_a?(String)
          config.build_settings[key] = val.split(' ').reject { |s| s == '-G' }.join(' ')
        end
      end
    end
  end
end
