// Mocks generated by Mockito 5.4.6 from annotations
// in leox/test/unit/providers/ai_resume_matcher_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:leox/backend/ai_workflows.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AIWorkflows].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIWorkflows extends _i1.Mock implements _i2.AIWorkflows {
  MockAIWorkflows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> parseResume({
    String? resumeFileUrl,
    String? resumeText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#parseResume, [], {
              #resumeFileUrl: resumeFileUrl,
              #resumeText: resumeText,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> matchResumeToJob({
    String? resumeUrl,
    String? resumeText,
    required String? jobDescription,
    Map<String, dynamic>? resumeData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#matchResumeToJob, [], {
              #resumeUrl: resumeUrl,
              #resumeText: resumeText,
              #jobDescription: jobDescription,
              #resumeData: resumeData,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> generateInterviewQuestions({
    required String? jobDescription,
    required String? resumeText,
    required String? interviewType,
    int? questionCount = 10,
    String? difficulty = 'medium',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateInterviewQuestions, [], {
              #jobDescription: jobDescription,
              #resumeText: resumeText,
              #interviewType: interviewType,
              #questionCount: questionCount,
              #difficulty: difficulty,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> optimizeProfile({
    required Map<String, dynamic>? profileData,
    required String? targetRole,
    List<String>? targetSkills,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#optimizeProfile, [], {
              #profileData: profileData,
              #targetRole: targetRole,
              #targetSkills: targetSkills,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> analyzeJobDescription({
    required String? jobDescription,
    required String? jobTitle,
    String? jobCategory,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeJobDescription, [], {
              #jobDescription: jobDescription,
              #jobTitle: jobTitle,
              #jobCategory: jobCategory,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> assessSkills({
    required Map<String, dynamic>? profileData,
    required List<Map<String, dynamic>>? experienceData,
    required List<String>? targetSkills,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#assessSkills, [], {
              #profileData: profileData,
              #experienceData: experienceData,
              #targetSkills: targetSkills,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getCareerRecommendations({
    required Map<String, dynamic>? profileData,
    required List<String>? interests,
    required List<String>? currentSkills,
    String? currentRole,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCareerRecommendations, [], {
              #profileData: profileData,
              #interests: interests,
              #currentSkills: currentSkills,
              #currentRole: currentRole,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}
